#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
add_worker_to_coordinator.sh
  Adds a worker to the Citus coordinator and triggers online rebalancing.

Flags:
  --host=<hostname>   Worker hostname as seen from coordinator (e.g., citus-worker2)
  --port=5432         Worker port (container's 5432; host port mapping is irrelevant inside the network)
  -h | --help         Show this help

Notes:
- This script expects a .env file with POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, and COORD_CONTAINER
  (generated by setup_citus_cluster.sh).
USAGE
}

HOST=""
PORT="5432"

for arg in "$@"; do
  case $arg in
    --host=*) HOST="${arg#*=}" ;;
    --port=*) PORT="${arg#*=}" ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown flag: $arg"; usage; exit 1 ;;
  esac
done

if [[ -z "${HOST}" ]]; then
  read -r -p "Worker hostname (e.g., citus-worker2): " HOST
fi
if [[ -z "${HOST}" ]]; then
  echo "Error: --host is required"; exit 1
fi

# Load credentials & coordinator name
if [[ ! -f .env ]]; then
  echo "Error: .env not found. Run setup_citus_cluster.sh first."; exit 1
fi
# shellcheck disable=SC2046
export $(grep -E '^(POSTGRES_USER|POSTGRES_PASSWORD|POSTGRES_DB|COORD_CONTAINER)=' .env | xargs)

echo "Adding worker ${HOST}:${PORT} to coordinator ${COORD_CONTAINER} ..."

# Use TCP inside the container so PGPASSWORD applies
docker exec -e PGPASSWORD="${POSTGRES_PASSWORD}" "${COORD_CONTAINER}" \
  psql -h 127.0.0.1 -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -v ON_ERROR_STOP=1 -c \
  "SELECT * FROM citus_add_node('${HOST}', ${PORT});"

echo "Current workers:"
docker exec -e PGPASSWORD="${POSTGRES_PASSWORD}" "${COORD_CONTAINER}" \
  psql -h 127.0.0.1 -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -c "SELECT * FROM citus_get_active_worker_nodes();"

echo "Starting online rebalancing ..."
docker exec -e PGPASSWORD="${POSTGRES_PASSWORD}" "${COORD_CONTAINER}" \
  psql -h 127.0.0.1 -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -v ON_ERROR_STOP=1 -c \
  "SELECT citus_rebalance_start();"

echo "Done. You can monitor progress from the coordinator with:"
echo "  docker exec -it ${COORD_CONTAINER} psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c \"SELECT * FROM citus_get_active_worker_nodes();\""
